# Generated by Django 3.2.5 on 2021-08-28 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bi_reports_illustrate_bot', '0002_auto_20210729_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='bi_reports_illustrate_bot.telegramuser'),
            preserve_default=False,
        ),
    ]
